<?php
/**
 * Append-only write audit storage.
 *
 * @package NotewareAdminTables
 */

declare(strict_types=1);

namespace Noteware\AdminTables\Audit;

use RuntimeException;
use Noteware\AdminTables\Model\StoredValue;

final class AuditRepository
{
    private const SCHEMA_VERSION = '3';

    /** How long a completed edit stays undoable from the list screen. */
    private const UNDO_WINDOW_SECONDS = 86400;

    private bool $transactionalTablesVerified = false;

    /** @var array<string, int> */
    private array $undoIndex = array();

    public function maybeInstall(): void
    {
        if (self::SCHEMA_VERSION !== get_option('nat_audit_schema_version')) {
            $this->install();
        }
    }

    public function install(): void
    {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';

        $charset = $wpdb->get_charset_collate();
        // The charset clause is generated by WordPress from the active database connection.
        // phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
        $sql = $wpdb->prepare("CREATE TABLE %i (
            id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            post_id bigint(20) unsigned NOT NULL,
            post_type varchar(64) NOT NULL,
            column_key varchar(191) NOT NULL,
            source varchar(32) NOT NULL,
            field_name varchar(191) NOT NULL,
            before_value longtext NOT NULL,
            after_value longtext NOT NULL,
            user_id bigint(20) unsigned NOT NULL,
            created_at datetime NOT NULL,
            undone_at datetime NULL,
            undone_by bigint(20) unsigned NULL,
            undo_audit_id bigint(20) unsigned NULL,
            is_undo tinyint(1) unsigned NOT NULL DEFAULT 0,
            PRIMARY KEY  (id),
            KEY post_column (post_id, column_key),
            KEY created_at (created_at)
        ) ENGINE=InnoDB {$charset};", $this->table());
        // phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
        dbDelta($sql);
        $this->assertTransactionalTables();
        update_option('nat_audit_schema_version', self::SCHEMA_VERSION, false);
    }

    /**
     * @param array{column_key: string, source: string, field_name: string} $descriptor Trusted adapter identifiers.
     * @param bool                                                          $isUndo     Whether this row records an undo.
     */
    public function record(int $postId, string $postType, array $descriptor, StoredValue $before, StoredValue $after, bool $isUndo = false): int
    {
        global $wpdb;
        $inserted = $wpdb->insert(
            $this->table(),
            array(
                'post_id'      => $postId,
                'post_type'    => $postType,
                'column_key'   => $descriptor['column_key'],
                'source'       => $descriptor['source'],
                'field_name'   => $descriptor['field_name'],
                'before_value' => wp_json_encode($before->toArray(), JSON_UNESCAPED_SLASHES),
                'after_value'  => wp_json_encode($after->toArray(), JSON_UNESCAPED_SLASHES),
                'user_id'      => get_current_user_id(),
                'created_at'   => current_time('mysql', true),
                'is_undo'      => $isUndo ? 1 : 0,
            ),
            array('%d', '%s', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%d')
        );
        if (false === $inserted) {
            throw new RuntimeException('The audit record could not be stored.');
        }
        return (int) $wpdb->insert_id;
    }

    /**
     * Load every still-undoable edit this user made on one page of records.
     *
     * This runs once per list screen so the undo control never costs a query
     * per rendered row.
     *
     * @param list<int> $postIds Page-scoped post IDs.
     */
    public function preloadUndoable(array $postIds, int $userId): void
    {
        $this->undoIndex = array();
        if (! $postIds || $userId < 1) {
            return;
        }

        global $wpdb;
        $placeholders = implode(', ', array_fill(0, count($postIds), '%d'));
        $since        = gmdate('Y-m-d H:i:s', time() - self::UNDO_WINDOW_SECONDS);
        // phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- The placeholder list is generated from a counted array of integers.
        $rows = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT id, post_id, column_key FROM %i
                 WHERE post_id IN ({$placeholders})
                   AND user_id = %d
                   AND undone_at IS NULL
                   AND is_undo = 0
                   AND created_at >= %s
                 ORDER BY id ASC",
                array_merge(array($this->table()), $postIds, array($userId, $since))
            ),
            ARRAY_A
        );
        // phpcs:enable WordPress.DB.PreparedSQL.InterpolatedNotPrepared

        foreach ((array) $rows as $row) {
            if (! is_array($row) || ! isset($row['id'], $row['post_id'], $row['column_key'])) {
                continue;
            }
            $this->undoIndex[$row['post_id'] . ':' . $row['column_key']] = (int) $row['id'];
        }
    }

    /** The most recent undoable edit id for one cell, if the page preloaded one. */
    public function undoableId(int $postId, string $columnKey): ?int
    {
        return $this->undoIndex[$postId . ':' . $columnKey] ?? null;
    }

    /** @return array<string, mixed>|null */
    public function find(int $auditId): ?array
    {
        global $wpdb;
        $row = $wpdb->get_row(
            $wpdb->prepare('SELECT * FROM %i WHERE id = %d', $this->table(), $auditId),
            ARRAY_A
        );
        return is_array($row) ? $row : null;
    }

    public function markUndone(int $auditId, int $undoAuditId): bool
    {
        global $wpdb;
        $updated = $wpdb->query(
            $wpdb->prepare(
                'UPDATE %i SET undone_at = %s, undone_by = %d, undo_audit_id = %d WHERE id = %d AND undone_at IS NULL',
                $this->table(),
                current_time('mysql', true),
                get_current_user_id(),
                $undoAuditId,
                $auditId
            )
        );
        return 1 === $updated;
    }

    public function begin(): void
    {
        global $wpdb;
        $this->assertTransactionalTables();
        if (false === $wpdb->query('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE')) {
            throw new RuntimeException('The edit transaction isolation level could not be set.');
        }
        if (false === $wpdb->query('START TRANSACTION')) {
            throw new RuntimeException('The edit transaction could not start.');
        }
    }

    public function commit(): void
    {
        global $wpdb;
        if (false === $wpdb->query('COMMIT')) {
            throw new RuntimeException('The edit transaction could not commit.');
        }
    }

    public function rollback(): void
    {
        global $wpdb;
        if (false === $wpdb->query('ROLLBACK')) {
            throw new RuntimeException('The edit transaction could not roll back.');
        }
    }

    private function table(): string
    {
        global $wpdb;
        return $wpdb->prefix . 'nat_edit_audit';
    }

    private function assertTransactionalTables(): void
    {
        if ($this->transactionalTablesVerified) {
            return;
        }

        global $wpdb;
        $rows = $wpdb->get_results(
            $wpdb->prepare(
                'SELECT TABLE_NAME, ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME IN (%s, %s)',
                $wpdb->postmeta,
                $this->table()
            ),
            ARRAY_A
        );
        $engines = array();
        foreach ($rows as $row) {
            if (isset($row['TABLE_NAME'], $row['ENGINE'])) {
                $engines[(string) $row['TABLE_NAME']] = strtoupper((string) $row['ENGINE']);
            }
        }
        if ('INNODB' !== ($engines[$wpdb->postmeta] ?? '') || 'INNODB' !== ($engines[$this->table()] ?? '')) {
            throw new RuntimeException('Editable metadata and audit storage must use the InnoDB transaction engine.');
        }
        $this->transactionalTablesVerified = true;
    }
}
